name: Deploy

on:
 push:
   branches:
     - lab1

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: akhileshns/heroku-deploy@v3.12.12
       with:
         heroku_api_key: ${{c13b037e-5696-4492-8cd5-bd09195a4883}}
         heroku_app_name: "stark-citadel-64325"
         heroku_email: "faghyt32@gmail.com"
         usedocker: true
